### ISSUE TITLE
Quote for adding in the visual composer

### ISSUE THREAD

**Issue by andygirvan** [thirtydigital/newrinkle#1]

**Comment by andygirvan** [comment]
Having had an investigation over the weekend, it looks like the theme is pretty baked in with their visual editor, so swapping to Visual Composer would require extensive work.

It is technically possible, however I would have to estimate it would take around 2 weeks to implement into a Visual Composer system.

The MAIN reason for this is that the existing theme does not appear to be build using the same Bootstrap framework, and it also implements inline styling into the markup, instead of using Bootstrap classes.

Here's some example Markup:
```
div class="motopress-wrapper content-holder clearfix">
	<div class="container">
		<div class="row">
						<div class="span12" data-motopress-wrapper-file="page-home.php" data-motopress-wrapper-type="content">
				<div class="row">
					<div class="span12" data-motopress-type="static" data-motopress-static-file="static/static-slider.php">
							<div class="slider_off"><!--slider off--></div>
					</div>
				</div>
				<div class="row">
					<div class="span12" data-motopress-type="loop" data-motopress-loop-file="loop/loop-page.php">
							<div id="post-203" class="page post-203 type-page status-publish hentry">
		<div class="hashAncor" id="aboutPage"></div>
<section class="lazy-load-box trigger effect-fade " data-delay="0" data-speed="800" style="-webkit-transition: all 800ms ease; -moz-transition: all 800ms ease; -ms-transition: all 800ms ease; -o-transition: all 800ms ease; transition: all 800ms ease;">
<div class="title-box clearfix "><h2 class="title-box_primary">Newrinkle</h2></div><!-- //.title-box -->
<h3 style="text-align: center;">
```

Things like `span12` are not bootstrap, and `text-align:center` is difficult to override using a different theme builder.

The 2 weeks would be to take the design of the theme, build it into Bootstrap and then install the Visual Composer plugin. 

As a resolution for this, it would be good if you could:

- Take a screenshot of the entire page as it is as the moment
- Annotate what areas you are having issues with styling (as seen in #4)
- Put sometime in to work through these together to get the theme looking as appropriate. I'd need to charge for these hours (but I imagine it would only be a 1 to 2 hour Skype call) as these are not in the original spec of the job (see: Additional text in section 2 of contract)

If these changes are not extensive enough, then I could formally quote up the work to rebuild the theme within the Visual Composer framework

Any questions, give me a buzz, if not let me know when you're free for a Skype call :)

**Comment by Amritx** [comment]
Hi Andy

that doesn't look like it will be cost effective, are there any other options you can think of to make it easier to use / edit /. style? 

If not what would be best option to implement the couple of amends I've requested?

**Comment by andygirvan** [comment]
I don't think so from a CMS point of view. I'd say the best thing to do would be to meet up and go through the amends you've listed, as the detail for them is a little vague and I don't want to accidentally amend things you're not wanting. Are you free this week @Amritx ?
